name: "Tests Python 3.4"
on: push
jobs:
  run:
    runs-on: ubuntu-18.04
    env:
      OS: ubuntu-18.04
      PYTHON: '3.4'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        pytest src/tests/*
